#!/bin/sh

PREREQ=""
prereqs()
{
   echo "$PREREQ"
}

case $1 in
prereqs)
   prereqs
   exit 0
   ;;
esac

# Begin real processing below this line

. /usr/share/initramfs-tools/hook-functions

echo -n "Copying extra-tools... "

TOOLS="/bin/sed /usr/bin/wc /usr/bin/rsync /usr/bin/dialog /usr/bin/awk"

for TOOL in ${TOOLS}; do
	if [ -x ${TOOL} ]; then
		copy_exec ${TOOL}
	else
		echo "No hay manera de usar $(basename ${TOOL}) arrancando con esta mierda de initramfs"
	fi
done

cp -r /etc/terminfo  "${DESTDIR}/etc"

for dir in /usr/share/terminfo/* /lib/terminfo/*; do
	mkdir -p ${DESTDIR}$dir
	for file in $dir/*; do
		copy_exec $file
	done
done

echo done!
