#!/bin/sh

. /scripts/libbsrt

TITLE="Punto de restauración"
TEXT="	Se va a proceder a realizar una congelación del estado actual del equipo. Esto permitirá volver a él en un futuro.\n\n\
	El proceso puede tardar varios minutos. Asegúrese de tener el equipo conectado a la corriente antes de continuar.\n\n\
¿Desea continuar?\n"
draw yesno || cancel_msg

TITLE="Creando punto de restauración..."
TEXT="No apague ni desconecte el equipo y, por favor, espere a que el proceso termine."
WIDTH=60
HEIGHT=10
chroot_dev ${ROOTDEV} rsnapshot -v ${INTERVAL} | \
	dialog ${BACKTITLE:+--backtitle "${BACKTITLE}"} \
	--no-collapse \
	--cr-wrap \
	${TITLE:+--title "${TITLE}"} \
	--progressbox "${TEXT}" \
	${HEIGHT:-0} ${WIDTH:-0} || cancel_msg
success_msg
