#!/bin/sh

set -e

if [ $DEBUG ]; then
	set -x
fi

. /etc/default/bsrt

mountroot () {
	sh
	reboot
}

check_dev () {
	TITLE="Comprobando dispositivos"
	TEXT="Esperando dispositivo $1..."
	while [ ! -b "$1" ]; do
		/bin/sleep 0.1 
		echo $(( ${slumber} - (${slumber} % 10) ))
		slumber=$(( ${slumber} + 1 ))
		[ ${slumber} -le 100 ] || panic "No existe el dispositivo $1"
	done || dialog ${BACKTITLE:+--backtitle "${BACKTITLE}"} \
		--no-collapse \
		--cr-wrap \
		${TITLE:+--title "${TITLE}"} \
		--progressbox "${TEXT}" \
		${HEIGHT:-0} ${WIDTH:-0}
}

is_mounted () {
	grep -q -o "^$1 " /etc/mtab
	return $?
}

mount_dev () {
	local opts=$1
	local srcdev=$2
	local mntpt=/mnt/${srcdev##*/}

	if ! is_mounted ${srcdev}; then
		mkdir -p ${mntpt}
		mount ${opts:+-o ${opts}} ${srcdev} ${mntpt}
	fi

	echo $mntpt
}

umount_dev () {
	umount $@
}

umount_all () {
	umount -alf 2> /dev/null || true
}

chroot_dev () {
	local devpt=$1; shift
	local mntpt=$(mount_dev rw $devpt)

	mount -o bind /dev $mntpt/dev/
	chroot $mntpt mount -a
	chroot $mntpt $@
	ERROR=$?
	chroot $mntpt umount -alf 2> /dev/null
	#umount $mntpt/dev/
	
	return $ERROR
}

backup_users () {
	chroot_dev $1 /bin/cp -a /etc/passwd /etc/shadow /etc/group /home
}

restore_users () {
	chroot_dev $1 /bin/cp -a /home/passwd /home/shadow /home/group /etc
}

cancel_msg () {
	TITLE="Proceso cancelado"
	TEXT="El proceso ha sido cancelado por el usuario, pulse ENTER para reiniciar.\n"
	WIDTH=50
	HEIGHT=5
	draw msgbox
	umount_all
	reboot
}

error_msg () {
	TITLE="Error"
	TEXT="Se ha producido un error. Contacte con su administrador. Pulse ENTER para reiniciar.\n"
	WIDTH=50
	HEIGHT=5
	draw msgbox
	umount_all
	reboot
}

success_msg () {
	TITLE="Fin"
	TEXT=${@:-"Proceso terminado, pulse ENTER para reiniciar.\n\n"}
	WIDTH=50
	draw msgbox
	umount_all
	reboot
}

draw () {
	local TYPE=${1:-msgbox}; shift
	case $TYPE in
		gauge|prgbox|programbox|progressbox)
			read data
			;;
	esac
	if [ ${DEBUG} ]; then
		echo "Pulse ENTER para dibujar la siguiente pantalla..."
		read
	fi

	echo ${data} | dialog ${COMMON_OPTS} ${BACKTITLE:+--backtitle "${BACKTITLE}"} --no-collapse --cr-wrap ${TITLE:+--title "${TITLE}"} --${TYPE} "${TEXT}" ${HEIGHT:-0} ${WIDTH:-0} $@
	ERROR=$?
	
	unset TEXT
	unset HEIGHT
	unset WIDTH

	return $ERROR
}

if echo ${ROOTDEV} | grep -q "^UUID="; then
	ROOTDEV=$(blkid -U ${ROOTDEV#UUID=})
fi
if echo ${BACKUPDEV} | grep -q "^UUID="; then
	BACKUPDEV=$(blkid -U ${BACKUPDEV#UUID=})
fi

if [ $DEBUG ]; then
	echo "ROOTDEV -> $ROOTDEV"
	echo "BACKUPDEV -> $BACKUPDEV"
	read
fi

check_dev ${ROOTDEV}

# Arreglar un fisco
if [ ${BACKUPDEV} == ${ROOTDEV} ]; then
	SNAPSHOTDIR=$(chroot_dev ${ROOTDEV} /bin/sed -n '/^snapshot_root/s/snapshot_root[[:blank:]]*//p' /etc/rsnapshot.conf)
else
	SNAPSHOTDIR="."
	check_dev ${BACKUPDEV}
fi
