#!/bin/bash
# Local filesystem mounting			-*- shell-script -*-

# Parameter: Where to mount the filesystem
#

. $(dirname $0)/libbsrt

syncronize () {
	TITLE="Restaurando $1 desde ${BACKUPDEV} a ${ROOTDEV}"
	TEXT="Completado..."
	mount_dev rw ${ROOTDEV} /mnt
	mount_dev ro ${BACKUPDEV} /mnt/${SNAPSHOTDIR}
	rsync -ax --progress --delete --exclude=/mnt/home --exclude=/mnt/${SNAPSHOTDIR} /mnt/$1/ /mnt/ | draw dialog
	umount ${BACKUPDEV}
	umount ${ROOTDEV}
}

getSnapshots() {
	mount_dev ro $BACKUPDEV /mnt

	for ID in $(ls -1 /mnt/${SNAPSHOTDIR}); do
		DATE=$(date -R -r ${SNAPSHOTDIR}/${ID} | sed 's/, \| /|/g')
		echo "${ID#*.} ${DATE}"
	done

	umount /mnt
}

mountroot () {
	menuitems=$(getSnapshots)

	TITLE="Selección del punto de restauración"
	TEXT="Elija punto de restauración a usar para llevar el equipo a un estado anterior:"
	dialog --title ${TITLE} --menu ${TEXT} 30 80 17 ${menuitems} 2> /tmp/answer || cancelmsg

	srcpoint_dir="${SNAPSHOTDIR}/daily.$(< /tmp/answer)"

	mount_dev ro ${BACKUPDEV} /mnt
	TITLE="Restauración del sistema"
	TEXT="\
		\n \
		\n   Se va a iniciar el proceso para restaurar la copia del sistema: \
		\n   $(date -R -r /mnt/${srcpoint_dir}) \
		\n \
		\n   ¿Desea continuar? \
		\n"
	draw yesno
	umount /mnt

	if [[ $? == 0 ]]; then
		clear
		syncronize $srcpoint_dir
	fi

	success_msg
}

mountroot
