#!/bin/sh
# Local filesystem mounting			-*- shell-script -*-

# Parameter: Where to mount the filesystem
#

. /scripts/libbsrt

syncronize () {
	SOURCE=$(mount_dev ro ${BACKUPDEV})
	TARGET=$(mount_dev rw ${ROOTDEV})

	TITLE="Restauración"
	TEXT="Restaurando $1 desde ${BACKUPDEV} a ${ROOTDEV}"
	rsync -ax --progress --delete ${SOURCE}/${SNAPSHOTDIR}/$1 ${TARGET}/ | draw programbox
	ERROR=$?
	
	return ${ERROR}
}

getSnapshots() {
	local mntpt=$(mount_dev ro ${BACKUPDEV})
	local numitems=0
	for ID in ${mntpt}/${SNAPSHOTDIR}/${1:-*}; do
		if ! echo ${ID} | grep -q -o "${INTERVAL}"; then
			continue
		fi
		DATE=$(date -R -r ${ID} | /bin/sed 's/, \| /_/g')
		menuitems="${ID##*.} ${DATE} ${SNAPSHOTS}"
		numitems=$(($numitems + 1))
	done
	umount ${mntpt}
	return $numitems
}

numitems=$(getSnapshots)

TITLE="Selección del punto de restauración"
TEXT="Elija punto de restauración a usar para llevar el equipo a un estado anterior:"
HEIGHT=30
WIDTH=50
draw menu ${numitems} ${menuitems} 2> /tmp/answer || cancel_msg

srcpoint_dir="${INTERVAL}.$(cat /tmp/answer)"

TITLE="Restauración del sistema"
TEXT="\
	\n \
	\n   Se va a iniciar el proceso para restaurar la copia del sistema: \
	\n   $(getSnapshots ${srcpoint_dir}) \
	\n \
	\n   ¿Desea continuar? \
	\n"
draw yesno || cancel_msg

syncronize $srcpoint_dir || error_msg

success_msg
