#!/bin/sh

. /scripts/libbsrt

HOME_PATH=/home/
ALL_USERS=$(chroot_dev ${ROOTDEV} /usr/bin/find ${HOME_PATH} -mindepth 1 -maxdepth 1 -type d ! -iname "lost+found" -printf "%f\n")
if [ -z "$ALL_USERS" ]; then
	TEXT="No existen usuarios en el sistema.\n"
	WIDTH=50
	HEIGHT=6
	success_msg ${TEXT} ${WIDTH} ${HEIGHT}
fi

numHomes=$(echo ${ALL_USERS} | tr ' ' '\n' | wc -l)

ITEMS="Todos $(chroot_dev ${ROOTDEV} /usr/bin/du -sh ${HOME_PATH} | cut -f 1)  0"
for USER in ${ALL_USERS}; do
	ITEMS="${ITEMS} ${USER} $(chroot_dev ${ROOTDEV} /usr/bin/du -sh ${HOME_PATH}/${USER} | cut -f 1) 0"
done

while [ ! "${SELECTED}" ]; do
	TITLE="Seleccion de usuario"
	TEXT="Seleccione los usuarios que desea eliminar.\n"
	WIDTH=60
	draw checklist $(( $numHomes + 1 )) ${ITEMS} 2> /tmp/listaUsuarios || cancel_msg
	SELECTED=$(sed 's/"//g' /tmp/listaUsuarios)
done

USERS=$(echo ${SELECTED} | sed 's/ /, /g')
TITLE="Confirmacion de borrado"
TEXT="Se va a proceder a borrar los siguientes usuarios: ${USERS}\n\n\
Este proceso borrara todos los datos de usuario y no se podra deshacer.\n\n\
¿Desea continuar?\n"
draw yesno || cancel_msg

if [ "${SELECTED}" == "Todos" ]; then
	SELECTED=${ALL_USERS}
fi

for USER in ${SELECTED}; do
	TITLE="Borrado de usuario"
	TEXT="Borrando ${USER}...\n"
	WIDTH=30
	{ echo 0;
	chroot_dev ${ROOTDEV} /usr/sbin/userdel -rf ${USER} 2> /dev/null || chroot_dev ${ROOTDEV} rm -rf /home/${USER} || true
	echo 100; } | draw gauge
done

backup_users ${ROOTDEV} || error_msg

success_msg
