#!/bin/sh

. /scripts/libbsrt

HOME_PATH=/home/
ALL_USERS=$(chroot_dev ${ROOTDEV} /bin/ls -1 ${HOME_PATH} | grep -v 'lost+found')

numHomes=$(echo ${ALL_USERS} | tr ' ' '\n' | wc -l)
if [ $numHomes -gt 0 ]; then
	ITEMS="Todos $(chroot_dev ${ROOTDEV} /usr/bin/du -sh $HOME_PATH | cut -f 1)  0"
else
	TEXT="No existen usuarios en el sistema."
	success_msg ${TEXT}
fi

for USER in ${ALL_USERS}; do
	ITEMS="${ITEMS} ${USER} $(chroot_dev ${ROOTDEV} /usr/bin/du -sh ${HOME_PATH}/${USER} | cut -f 1) 0"
done

while [ ! ${SELECTED} ]; do
	TITLE="Selección de usuario"
	TEXT="Seleccione los usuarios que desea eliminar"
	WIDTH=50
	HEIGHT=10
	draw checklist $numHomes ${ITEMS} 2> /tmp/listaUsuarios || cancel_msg
	SELECTED=$(sed 's/"//g' /tmp/listaUsuarios)
done

if [ "${SELECTED}" == "Todos" ]; then
	echo "Borrando todos los usuarios"
	SELECTED=${ALL_USERS}
fi

for USER in ${SELECTED}; do
	TITLE="Borrado de usuario"
	TEXT="Borrando ${USER}..."
	{ echo 0;
	chroot_dev ${ROOTDEV} /usr/sbin/userdel -rf ${USER} || error_msg
	echo 100; } | draw gauge
done

success_msg
