#!/bin/sh

set -e

if [ "$1" = "-v" ]; then
	VERBOSE="-v"
fi

ID=$(getSystemId --service-tag | sed "s/Service Tag: *//")
VERSION=$(lsb_release -ds | tr " " "-")
PPNAME=$(ps -p $PPID -o comm=)

echo Committing system changes... This may take some time.
( test -e /etc/rsnapshot.conf && test -x /usr/bin/rsnapshot && rsnapshot $VERBOSE sync) || exit 1

# Rotate snapshots

INTERVAL=$(awk '$0 !~ /^ *#/ && $1 == "retain" { print $2 }' /etc/rsnapshot.conf)
[ -z $INTERVAL ] && exit 0

mount.snapdir
rsnapshot $VERBOSE $INTERVAL
wget -q -t 2 "http://osl.ull.es/bull/log.php?id=${ID}&update=${VERSION}&ok=${PPNAME}" -O /dev/null &
umount.snapdir
