#!/bin/sh
cat << EOF
menuentry "Crear usuario" {
	linux /vmlinuz root=${GRUB_DEVICE} ro quiet boot=useradd
	initrd /initrd.img
}

submenu --users="admin master" "[Menu administrativo]" {
menuentry "Borrar usuarios" {
        linux /vmlinuz root=${GRUB_DEVICE} ro quiet boot=userdel
        initrd /initrd.img
}
menuentry "Restaurar sistema" {
        linux /vmlinuz root=${GRUB_DEVICE} ro quiet boot=restore
        initrd /initrd.img
}
menuentry --users="master" "Crear punto de restauración" {
        linux /vmlinuz root=${GRUB_DEVICE} ro quiet boot=backup
        initrd /initrd.img
}
#menuentry --users="master" "Clonar sistema" {
#        linux /vmlinuz root=${GRUB_DEVICE} ro quiet boot=udpcast
#        initrd /initrd.img
#}
}
EOF
