#!/bin/sh
cat << EOF
menuentry "Crear usuario" {
	linux /vmlinuz root=${GRUB_DEVICE} ro quiet boot=useradd
	initrd /initrd.img
}

submenu "[Menu administrativo]" {
menuentry --users admin "Borrar usuarios" {
        linux /vmlinuz root=${GRUB_DEVICE} ro quiet boot=userdel
        initrd /initrd.img
}
menuentry --users admin "Restaurar sistema" {
        linux /vmlinuz root=${GRUB_DEVICE} ro quiet boot=restore
        initrd /initrd.img
}
#menuentry "Clonar sistema" {
#        linux /vmlinuz root=${GRUB_DEVICE} ro quiet boot=udpcast
#        initrd /initrd.img
#}
}
EOF
