#!/bin/bash

set -e

BUILDDIR="${BUILDDIR:-/tmp/buildd}"

install_packages() {
    apt-get -y "${APTGETOPT[@]}" install "$@"
}

install_packages lintian

echo "+++ lintian output +++"

#su -c "lintian -I --show-overrides "$BUILDDIR"/*.changes" - pbuilder
# use this version if you don't want lintian to fail the build
su -c "lintian -I --show-overrides "$BUILDDIR"/*.changes; :" - pbuilder

echo "+++ end of lintian output +++"

