#!/bin/bash
# example file to be used with --hookdir
#
# 343894: a script to run debc command, contributed from q-funk.

BUILDDIR="${BUILDDIR:-/tmp/buildd}"
apt-get install -y "${APTGETOPT[@]}" devscripts
cd "$BUILDDIR"/*/debian
cd ..
debc
#EOF
