#!/bin/bash
# example file to be used with --hookdir
#
# 343894: a script to run debc command, contributed from q-funk.

apt-get install -y --allow-downgrades --allow-remove-essential --allow-change-held-packages devscripts
cd /tmp/buildd/*/debian
cd ..
debc
#EOF
