#!/bin/bash
# example file to be used with --hookdir
#
# invoke shell if build fails.

apt-get install -y --allow-downgrades --allow-remove-essential --allow-change-held-packages vim less 
cd /tmp/buildd/*/debian/..
/bin/bash < /dev/tty > /dev/tty 2> /dev/tty
#EOF
